// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manticora.Infrastructure.Migrations
{
    [DbContext(typeof(ManticoraDbContext))]
    partial class ManticoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Attack", b =>
                {
                    b.Property<int>("AttackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttackDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CityDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManticoreDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttackId");

                    b.HasIndex("DefenderId");

                    b.HasIndex("GameId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.AttackingNation", b =>
                {
                    b.Property<int>("AttackingNationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttackingNationId");

                    b.ToTable("AttackingNations");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Defender", b =>
                {
                    b.Property<int>("DefenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.HasKey("DefenderId");

                    b.HasIndex("GameId");

                    b.ToTable("Defenders");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackingNationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ManticoreHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.HasIndex("AttackingNationId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryId");

                    b.HasIndex("DefenderId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            WeaponId = 1,
                            Cost = 80,
                            Name = "Gran cañón",
                            Range = 50
                        },
                        new
                        {
                            WeaponId = 2,
                            Cost = 60,
                            Name = "Metralla",
                            Range = 40
                        },
                        new
                        {
                            WeaponId = 3,
                            Cost = 50,
                            Name = "Mosquete",
                            Range = 30
                        },
                        new
                        {
                            WeaponId = 4,
                            Cost = 30,
                            Name = "Pistola",
                            Range = 20
                        },
                        new
                        {
                            WeaponId = 5,
                            Cost = 10,
                            Name = "Granada",
                            Range = 10
                        });
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Attack", b =>
                {
                    b.HasOne("Manticora.Domain.Entities.Db.Defender", "Defender")
                        .WithMany("Attacks")
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manticora.Domain.Entities.Db.Game", "Game")
                        .WithMany("Attacks")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manticora.Domain.Entities.Db.Weapon", "Weapon")
                        .WithMany("Attacks")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defender");

                    b.Navigation("Game");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Defender", b =>
                {
                    b.HasOne("Manticora.Domain.Entities.Db.Game", null)
                        .WithMany("Defenders")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Game", b =>
                {
                    b.HasOne("Manticora.Domain.Entities.Db.AttackingNation", "AttackingNation")
                        .WithMany("Games")
                        .HasForeignKey("AttackingNationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttackingNation");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Inventory", b =>
                {
                    b.HasOne("Manticora.Domain.Entities.Db.Defender", "Defender")
                        .WithMany("Inventories")
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manticora.Domain.Entities.Db.Weapon", "Weapon")
                        .WithMany("Inventories")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defender");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.AttackingNation", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Defender", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Game", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("Defenders");
                });

            modelBuilder.Entity("Manticora.Domain.Entities.Db.Weapon", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
